spring:
  application:
    name: EventsManagerSber
  datasource:
#    url: jdbc:postgresql://localhost:5432/EventsSber?currentSchema=second_scheme
    url: jdbc:postgresql://localhost:5432/EventsSber
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true