spring:
  application:
    name: EventsManagerSber
  datasource:
    url: jdbc:postgresql://localhost:5432/EventsSber
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
